name: CI

on:
  
  push:
  workflow_dispatch:

jobs:
  
  pipeline:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3

      - name: CheckOut
        run: |
          echo "CheckOut@v3"

      - name: Build & U.Test
        run: |
          chmod +x gradlew
          ./gradlew build
          ./gradlew test
      
      - name: SonarCloud
        run: |
          chmod +x gradlew
          ./gradlew sonar -Dsonar.token=${{secrets.TOKEN_SONARCLOUD}}
