name: CI

on:
  
  push:
  workflow_dispatch:

jobs:
  
  pipeline:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Unit Test
        run: |
          chmod +x gradlew
          ./gradlew jacocoTestCoverageVerification
      
      - name: SonarCloud Code Review
        run: |
          chmod +x gradlew
          ./gradlew sonar -Dsonar.token=${{secrets.TOKEN_SONARCLOUD}} --info --stacktrace

      - name: SonarCloud Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.TOKEN_SONARCLOUD }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          scanMetadataReportFile: build/sonar/report-task.txt
  deploy: 
    runs-on: self-hosted 
    needs: pipeline
    steps: 

    - uses: actions/checkout@v3
    
    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yml
